Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2022-10, with the labels that each got.

#201 Fix compiling bas files relative to the CWD
  source/qb64pe.bas
  tests/compile_tests.sh
  tests/compile_tests/extra/include_extra.bi
  tests/compile_tests/extra/include_extra_include.bi
  tests/compile_tests/extra/include_extra_target.bi
  tests/compile_tests/include_paths/include_fixed_compile_location.bas
  tests/compile_tests/include_paths/include_fixed_compile_location.output
  tests/compile_tests/include_paths/include_multiple.bas
  tests/compile_tests/include_paths/include_multiple.output
  tests/compile_tests/include_paths/include_relative.bas
  tests/compile_tests/include_paths/include_relative.output
Labels: bug

#202 Fix `String * n` and `Bit * n` when used with `Static` arrays.
  source/qb64pe.bas
  tests/compile_tests/types/all_types.bas
  tests/compile_tests/types/all_types.output
  tests/compile_tests/types/dim.bas
  tests/compile_tests/types/dim.output
  tests/compile_tests/types/dim_array.bas
  tests/compile_tests/types/dim_array.output
  tests/compile_tests/types/dim_bad_bit_no_length.bas
  tests/compile_tests/types/dim_bad_bit_no_length.err
  tests/compile_tests/types/dim_bad_string_no_length.bas
  tests/compile_tests/types/dim_bad_string_no_length.err
  tests/compile_tests/types/dim_bad_typename_byte.bas
  tests/compile_tests/types/dim_bad_typename_byte.err
  tests/compile_tests/types/dim_bad_typename_string.bas
  tests/compile_tests/types/dim_bad_typename_string.err
  tests/compile_tests/types/static.bas
  tests/compile_tests/types/static.output
  tests/compile_tests/types/static_array.bas
  tests/compile_tests/types/static_array.output
  tests/compile_tests/types/static_bad_bit_no_length.bas
  tests/compile_tests/types/static_bad_bit_no_length.err
  tests/compile_tests/types/static_bad_string_no_length.bas
  tests/compile_tests/types/static_bad_string_no_length.err
  tests/compile_tests/types/static_bad_typename_byte.bas
  tests/compile_tests/types/static_bad_typename_byte.err
  tests/compile_tests/types/static_bad_typename_string.bas
  tests/compile_tests/types/static_bad_typename_string.err
Labels: bug

#203 Add and fix options listed in manpage
  qb64pe.1
Labels: documentation

#208 Implement `_SNDPLAYCOPY` enhancement #185
  internal/c/libqb/include/audio.h
  internal/c/parts/audio/audio.cpp
  internal/c/parts/audio/out/src.c
  internal/c/qbx.cpp
  source/subs_functions/subs_functions.bas
Labels: enhancement

#210 Version 3.3.0
  source/global/version.bas
Labels: enhancement

#222 Fix setup_osx.command script when run from a different directory
  setup_osx.command
  tests/dist_tests.sh
Labels: bug

#225 Update `tinyfiledialogs` to v3.8.9
  internal/c/parts/gui/tinyfiledialogs.c
  internal/c/parts/gui/tinyfiledialogs.h
Labels: bug

#227 Fix _OPENFILEDIALOG$ to accept -1 for allowMultipleSelects&
  internal/c/parts/gui/gui.cpp
Labels: bug

#228 Version 3.4.0
  source/global/version.bas
Labels: enhancement
