Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2022-05, with the labels that each got.

#41 Fix text wrapping on last column with variable width fonts
  internal/c/libqb.cpp
  tests/.gitignore
  tests/qbasic_tests.sh
Labels: bug

#42 Use $EXEICON and $VERSIONINFO in qb64.bas, replacing the existing icon.rc file
  source/global/version.bas
  source/icon.rc
  source/qb64.bas
Labels: enhancement

#56 Fix quoting in Windows-specific files in ./internal/source
  internal/source/icon.rc
  internal/source/manifest.h
  internal/source/qb64.manifest
Labels: bug

#58 Add error handling to setup_win.bat, fix objcopy command
  Makefile
  setup_win.bat
Labels: bug

#60 Fix to _desktopwidth, _desktopheight, _screenicon
  internal/c/libqb.cpp
Labels: bug

#82 Fix various identified Makefile issues
  Makefile
  source/global/version.bas
  source/qb64.bas
  tests/compile_tests.sh
Labels: bug

#84 Add missing test for directory with spaces
  tests/compile_tests/name with spaces/test.bas
  tests/compile_tests/name with spaces/test.output
Labels: enhancement

#86 Remove 32-bit/64-bit distinction from Linux and OSX artifact name
  .github/workflows/ci.yml
Labels: bug

#85 Add documentation of the build system
  docs/build-system.md
Labels: documentation

#87 Add ide compiler settings dialog
  Makefile
  docs/build-system.md
  setup_lnx.sh
  setup_osx.command
  source/global/IDEsettings.bas
  source/ide/ide_methods.bas
  source/qb64.bas
  source/utilities/strings.bas
Labels: enhancement
