Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2023-10, with the labels that each got.

#380 Initial WoA64 and MingW-LLVM support
  internal/c/libqb.cpp
  internal/c/libqb/include/libqb-common.h
  setup_mingw.cmd
  setup_win.cmd
  source/qb64pe.bas
Labels: enhancement

#384 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#385 Fix menu item `Run #Only (No EXE)`
  source/ide/ide_methods.bas
Labels: bug

#387 Use correct math functions from std::
  internal/c/common.h
  internal/c/libqb.cpp
  internal/c/qbx.cpp
Labels: bug

#389 Use correct math functions from std:: in qb64pe.bas and subs_functions.bas
  source/qb64pe.bas
  source/subs_functions/subs_functions.bas
Labels: bug

#391 Avoid miniaudio runtime linking on macOS
  Makefile
  internal/c/parts/audio/miniaudio_impl.cpp
Labels: bug

#392 $VERSIONINFO enhancement (#20)
  .gitignore
  source/qb64pe.bas
  source/utilities/strings.bas
Labels: enhancement

#399 Wait for key release before running
  source/ide/ide_methods.bas
Labels: bug

#401 Add Support for optional paramter for an image handle to CLS
  internal/c/libqb.cpp
  internal/c/qbx.cpp
  source/subs_functions/subs_functions.bas
Labels: enhancement

#405 Patch _ARCSEC and _ARCCSC
  internal/c/libqb.cpp
  internal/c/libqb/include/extended_math.h
  internal/c/qbx.cpp
  source/qb64pe.bas
  tests/compile_tests/const/math_funcs.bas
Labels: bug
