Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2023-09, with the labels that each got.

#365 Patch to CopyFile
  source/utilities/file.bas
Labels: bug

#366 Bug fix for CONST Blink with $NOPREFIX
  internal/support/color/color0_noprefix.bi
Labels: bug

#367 Support for PCF & BDF fonts
  .gitignore
  internal/c/parts/video/font/font.cpp
Labels: bug, enhancement

#368 Image library enhancements
  Makefile
  internal/c/libqb.cpp
  internal/c/libqb.h
  internal/c/libqb/include/image.h
  internal/c/parts/video/image/image.cpp
  internal/c/parts/video/image/nanosvg/nanosvg.h
  internal/c/parts/video/image/nanosvg/nanosvgrast.h
  internal/c/parts/video/image/pixelscalers/hqx.hpp
  internal/c/parts/video/image/pixelscalers/mmpx.hpp
  internal/c/parts/video/image/pixelscalers/sxbr.hpp
  internal/c/parts/video/image/qoi.h
  internal/c/parts/video/image/stb/stb_image.h
  internal/c/parts/video/image/stb/stb_image_write.h
  licenses/README.md
  licenses/license_dr_pcx.txt
  licenses/license_hqx.txt
  licenses/license_mmpx.txt
  licenses/license_nanosvg.txt
  licenses/license_qoi.txt
  licenses/license_stb_image_write.txt
  licenses/license_sxbr.txt
  source/subs_functions/subs_functions.bas
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/image/test.lnx.license
  tests/compile_tests/image/test.osx.license
  tests/compile_tests/image/test.win.license
Labels: enhancement

#370 Audio enhancements
  Makefile
  internal/c/parts/audio/extras/build.mk
  internal/c/parts/audio/extras/hively_ma_vtable.cpp
  internal/c/parts/audio/extras/hivelytracker/hvl_replay.c
  internal/c/parts/audio/extras/midi_ma_vtable.cpp
  internal/c/parts/audio/extras/mod_ma_vtable.cpp
  internal/c/parts/audio/extras/qoa.h
  internal/c/parts/audio/extras/qoa_ma_vtable.cpp
  internal/c/parts/audio/extras/radv2_ma_vtable.cpp
  internal/c/parts/audio/extras/tinysoundfont/tsf.h
  internal/c/parts/audio/extras/vtables.h
  internal/c/parts/audio/miniaudio.h
  internal/c/parts/audio/miniaudio_impl.cpp
  licenses/README.md
  licenses/license_miniaudio.txt
  licenses/license_qoa.txt
  licenses/license_radv2.txt
  tests/compile_tests/audio_out/test.lnx.license
  tests/compile_tests/audio_out/test.osx.license
  tests/compile_tests/audio_out/test.win.license
  tests/compile_tests/midi/test.lnx.license
  tests/compile_tests/midi/test.osx.license
  tests/compile_tests/midi/test.win.license
Labels: bug, enhancement

#371 Update to GCC-13.1.0 with MinGW runtime v11
  setup_mingw.cmd
Labels: enhancement

#372 Print spaces and tabs correctly when _KEEPBACKGROUND is set
  internal/c/libqb.cpp
Labels: bug

#373 Feature request
  source/ide/ide_methods.bas
Labels: enhancement

#378 Remove usage of `using namespace std` from libqb
  internal/c/libqb.cpp
  internal/c/parts/input/game_controller/src.c
Labels: enhancement
