Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2024-11, with the labels that each got.

#565 The big audio library update
  internal/c/libqb.cpp
  internal/c/libqb/include/audio.h
  internal/c/libqb/include/image.h
  internal/c/parts/audio/audio.cpp
  internal/c/parts/audio/build.mk
  internal/c/parts/audio/extras/build.mk
  internal/c/parts/audio/extras/foo_midi/MIDIPlayer.cpp
  internal/c/parts/audio/extras/foo_midi/VSTiPlayer.cpp
  internal/c/parts/audio/extras/libmidi/Support.h
  internal/c/parts/audio/extras/midi_ma_vtable.cpp
  internal/c/parts/audio/extras/qoa_ma_vtable.cpp
  internal/c/parts/audio/extras/ymfmidi/player.cpp
  internal/c/parts/audio/extras/ymfmidi/player.h
  internal/c/parts/audio/framework.h
  internal/c/parts/gui/gui.cpp
  internal/c/parts/gui/tinyfiledialogs.c
  source/qb64pe.bas
  source/subs_functions/subs_functions.bas
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/audio_mem_test/sndopen_mem_test.bas
  tests/compile_tests/audio_mem_test/sndopen_mem_test.output
Labels: bug, enhancement, libqb-refactor

#564 Move to macOS 13 runner and update to latest supported LLVM MinGW
  .github/workflows/build-process.yml
  setup_lnx.sh
  setup_mingw.cmd
  setup_osx.command
  setup_win.cmd
Labels: enhancement

#568 miniaudio file name hashing fix
  internal/c/libqb/include/audio.h
  internal/c/libqb/include/libqb-common.h
  internal/c/parts/audio/audio.cpp
  internal/c/parts/audio/extras/libmidi/framework.h
  internal/c/parts/audio/extras/midi_ma_vtable.cpp
  internal/c/parts/audio/extras/qoa.h
  internal/c/parts/audio/extras/radv2_ma_vtable.cpp
  internal/c/parts/audio/framework.cpp
  internal/c/parts/audio/framework.h
  internal/c/parts/video/image/image.cpp
Labels: bug, enhancement

#570 Do not throw an error if voice is out of range in func_play()
  internal/c/parts/audio/audio.cpp
Labels: bug

#571 Fix export as Wiki example
  source/ide/ide_export.bas
Labels: bug

#572 Export adjustment
  source/ide/ide_export.bas
Labels: enhancement

#573 Avoid calling BufferMap::ReleaseBuffer() from VFS::OnClose()
  internal/c/parts/audio/audio.cpp
  internal/c/parts/audio/extras/primesynth/primesynth.cpp
Labels: bug

#574 Implement _IIF and fix _ROR & _ROL
  internal/c/libqb/include/bitops.h
  source/qb64pe.bas
  source/subs_functions/subs_functions.bas
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/iif/iif_test.bas
  tests/compile_tests/iif/iif_test.output
Labels: bug, enhancement

#581 Remove _OFFSET restrictions and implement _CAST
  source/qb64pe.bas
  source/subs_functions/subs_functions.bas
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/cast/cast_test.bas
  tests/compile_tests/cast/cast_test.output
  tests/compile_tests/offset/offset_test.bas
  tests/compile_tests/offset/offset_test.output
Labels: bug, enhancement
