Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2024-09, with the labels that each got.

#534 Allow _MIDISOUNDBANK to use the default soundbank
  internal/c/parts/audio/audio.cpp
  internal/c/parts/audio/extras/foo_midi/InstrumentBankManager.cpp
  internal/c/parts/audio/extras/foo_midi/InstrumentBankManager.h
  internal/c/parts/audio/extras/foo_midi/VSTiPlayer.cpp
  internal/c/parts/audio/extras/midi_ma_vtable.cpp
Labels: enhancement

#535 Relax ALIAS function name validation
  source/global/constants.bas
  source/qb64pe.bas
  tests/compile_tests/extra/declare-header.bi
  tests/compile_tests/extra/header-dir/fastmath-extra.h
Labels: bug, enhancement

#536 Export enhancement
  source/ide/ide_methods.bas
Labels: enhancement

#537 Export fixes
  source/ide/ide_methods.bas
Labels: bug

#538 Enable globbing by default when using llvm-mingw
  internal/c/qbx.cpp
Labels: bug, enhancement

#539 Update setup_mingw.cmd to use LLVM MinGW on all versions of Windows
  setup_mingw.cmd
  source/qb64pe.bas
  source/utilities/s-buffer/readme.txt
  source/utilities/s-buffer/simplebuffer.bi
  source/utilities/s-buffer/simplebuffer.bm
  tests/dist_tests.sh
Labels: enhancement

#540 Silence C++ compiler warnings
  internal/c/common.h
  internal/c/libqb.cpp
  internal/c/libqb/include/extended_math.h
  internal/c/libqb/include/game_controller.h
  internal/c/libqb/include/mac-mouse-support.h
  internal/c/libqb/include/qbs.h
  internal/c/libqb/src/datetime.cpp
  internal/c/libqb/src/filepath.cpp
  internal/c/libqb/src/glut-main-thread.cpp
  internal/c/libqb/src/http-stub.cpp
  internal/c/libqb/src/qbs.cpp
  internal/c/libqb/src/qbs_cmem.cpp
  internal/c/libqb/src/qbs_mk_cv.cpp
  internal/c/libqb/src/shell.cpp
  internal/c/parts/gui/tinyfiledialogs.c
  internal/c/parts/input/game_controller/game_controller.cpp
  internal/c/qbx.cpp
  source/ide/ide_methods.bas
Labels: enhancement

#544 Deprecating $NOPREFIX
  internal/support/color/color0_noprefix.bi
  internal/support/color/color32_noprefix.bi
  source/ide/ide_methods.bas
  source/qb64pe.bas
  source/subs_functions/extensions/opengl/opengl_methods.bas
  source/subs_functions/subs_functions.bas
  source/utilities/const_eval.bas
  source/utilities/type.bas
  tests/compile_tests/const/noprefix.bas
  tests/compile_tests/const/noprefix.output
  tests/compile_tests/http/statuscode_noprefix_missing.bas
  tests/compile_tests/http/statuscode_noprefix_missing.err
  tests/compile_tests/http/statuscode_unstable.bas
  tests/compile_tests/http/statuscode_unstable_noprefix.bas
  tests/compile_tests/types/all_types.bas
  tests/compile_tests/types/dim.bas
  tests/compile_tests/types/dim_array.bas
  tests/compile_tests/types/static.bas
  tests/compile_tests/types/static_array.bas
Labels: enhancement, const-issues

#547 Silence WoA C++ compiler warnings
  internal/c/libqb/build.mk
  internal/c/libqb/include/qbs.h
  internal/c/libqb/include/rounding.h
  internal/c/libqb/src/rounding.cpp
Labels: enhancement

#546 Fix #541 and update clip library
  Makefile
  internal/c/parts/os/clipboard/build.mk
  internal/c/parts/os/clipboard/clip/clip.cpp
  internal/c/parts/os/clipboard/clip/clip.h
  internal/c/parts/os/clipboard/clip/clip_common.h
  internal/c/parts/os/clipboard/clip/clip_lock_impl.h
  internal/c/parts/os/clipboard/clip/clip_osx.h
  internal/c/parts/os/clipboard/clip/clip_osx.mm
  internal/c/parts/os/clipboard/clip/clip_win.cpp
  internal/c/parts/os/clipboard/clip/clip_win.h
  internal/c/parts/os/clipboard/clip/clip_win_bmp.cpp
  internal/c/parts/os/clipboard/clip/clip_win_bmp.h
  internal/c/parts/os/clipboard/clip/clip_win_wic.cpp
  internal/c/parts/os/clipboard/clip/clip_win_wic.h
  internal/c/parts/os/clipboard/clipboard.cpp
  tests/compile_tests/clipboard/clipboard_test.bas
  tests/compile_tests/clipboard/clipboard_test.output
Labels: bug

#548 Finalize $NOPREFIX deprecation
  source/qb64pe.bas
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/console_only/midi.bas
  tests/compile_tests/console_only/test-soundfont.sf2
  tests/compile_tests/midi/custom-soundfont.bas
  tests/compile_tests/midi/custom-soundfont.output
  tests/compile_tests/midi/include/soundfont.bi
  tests/compile_tests/midi/include/soundfont.sf3
  tests/compile_tests/midi/midisoundbank_embed_test.bas
  tests/compile_tests/midi/midisoundbank_embed_test.output
  tests/compile_tests/midi/midisoundbank_file_test.bas
  tests/compile_tests/midi/midisoundbank_file_test.output
  tests/compile_tests/midi/midisoundbank_memory_test.bas
  tests/compile_tests/midi/midisoundbank_memory_test.output
  tests/compile_tests/midi/midisoundfont_no_unstable.bas
  tests/compile_tests/midi/midisoundfont_no_unstable.err
  tests/compile_tests/midi/relative_to_include.bas
  tests/compile_tests/midi/relative_to_include.compile-from-base
  tests/compile_tests/midi/relative_to_source.bas
  tests/compile_tests/midi/relative_to_source.compile-from-base
Labels: enhancement
