Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2024-06, with the labels that each got.

#501 Make _FILES$ default to "*" if fileSpec$ is an empty string
  internal/c/libqb/src/filesystem.cpp
  tests/compile_tests/filesystem/filesys_test.bas
  tests/compile_tests/filesystem/filesys_test.output
Labels: bug

#503 Font fixes
  internal/c/libqb.cpp
  internal/c/libqb/include/font.h
  internal/c/parts/video/font/font.cpp
  internal/c/parts/video/font/stub_font.cpp
  source/subs_functions/subs_functions.bas
  tests/compile_tests/filesystem/filesys_test.bas
  tests/compile_tests/font/test.bas
  tests/compile_tests/font/test.output
  tests/compile_tests/font/test06u.bmp
  tests/compile_tests/font/test07u.bmp
  tests/compile_tests/font/test08u.bmp
  tests/compile_tests/font/test09u.bmp
  tests/compile_tests/font/test10u.bmp
  tests/compile_tests/font/test11u.bmp
  tests/compile_tests/font/test13u.bmp
  tests/compile_tests/font/test15u.bmp
  tests/compile_tests/utilities/imageassert.bm
Labels: bug, enhancement

#506 Wiki stuff
  source/ide/ide_methods.bas
  source/ide/wiki/wiki_methods.bas
Labels: bug, enhancement

#512 Migrate to buffered search/recent files histories
  source/ide/ide_methods.bas
  source/utilities/file.bas
  source/utilities/s-buffer/simplebuffer.bi
  source/utilities/s-buffer/simplebuffer.bm
Labels: enhancement
