Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2024-04, with the labels that each got.

#475 Clipboard fixes
  .github/workflows/build-process.yml
  Makefile
  internal/c/libqb.cpp
  internal/c/libqb/include/clipboard.h
  internal/c/libqb/include/image.h
  internal/c/parts/core/freeglut/freeglut_main.c
  internal/c/parts/gui/gui.cpp
  internal/c/parts/os/clipboard/build.mk
  internal/c/parts/os/clipboard/clip/clip.cpp
  internal/c/parts/os/clipboard/clip/clip.h
  internal/c/parts/os/clipboard/clip/clip_common.h
  internal/c/parts/os/clipboard/clip/clip_lock_impl.h
  internal/c/parts/os/clipboard/clip/clip_osx.mm
  internal/c/parts/os/clipboard/clip/clip_win.cpp
  internal/c/parts/os/clipboard/clip/clip_win_wic.h
  internal/c/parts/os/clipboard/clip/clip_x11.cpp
  internal/c/parts/os/clipboard/clip/clip_x11_png.h
  internal/c/parts/os/clipboard/clip/image.cpp
  internal/c/parts/os/clipboard/clipboard.cpp
  internal/c/parts/video/font/font.cpp
  internal/c/parts/video/image/image.cpp
  internal/c/qbx.cpp
  licenses/README.md
  licenses/license_clip.txt
  setup_lnx.sh
  source/qb64pe.bas
  tests/compile_tests/clipboard/clipboard_test.bas
  tests/compile_tests/clipboard/clipboard_test.output
Labels: bug, enhancement

#477 Open GUI file dialog when Ctrl+S is pressed
  source/ide/ide_methods.bas
Labels: bug

#478 Logical Boolean operators
  source/qb64pe.bas
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/bool_test/bool_test.bas
  tests/compile_tests/bool_test/bool_test.output
Labels: enhancement

#480 Fix mono-mode font rendering issues
  internal/c/parts/video/font/font.cpp
Labels: bug

#481 Create Windows GUI applications only when both DEP_CONSOLE_ONLY & DEP_CONSOLE are not defined
  Makefile
Labels: bug

#484 Fix NOT, _NEGATE, and macOS startup script bugs
  source/qb64pe.bas
  tests/compile_tests/bool_test/bool_test.bas
  tests/compile_tests/operators_test/op_exp.bas
  tests/compile_tests/operators_test/op_exp.output
Labels: bug

#485 Wiki fixes
  source/ide/ide_methods.bas
  source/ide/wiki/wiki_global.bas
Labels: bug
