Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2024-08, with the labels that each got.

#525 More ide refactoring
  source/ide/config/cfg_methods.bas
  source/ide/ide_global.bas
  source/ide/ide_methods.bas
  source/ide/wiki/wiki_methods.bas
  source/qb64pe.bas
  source/subs_functions/subs_functions.bas
  source/utilities/strings.bas
Labels: enhancement

#530 Fixes and enhancements
  internal/c/libqb/include/error_handle.h
  internal/c/libqb/src/error_handle.cpp
  internal/c/qbx.cpp
  source/ide/config/cfg_methods.bas
  source/ide/ide_methods.bas
  source/qb64pe.bas
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/on_error/errtest.bas
  tests/compile_tests/on_error/errtest.h
  tests/compile_tests/on_error/errtest.output
Labels: bug, enhancement

#531 Add _NEWHANDLER option for ON ERROR GOTO...
  source/qb64pe.bas
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/on_error/errtest.bas
  tests/compile_tests/on_error/errtest.output
Labels: bug, enhancement

#533 Use std::hash to generate a proper unique key in _SNDOPEN
  internal/c/parts/audio/audio.cpp
  internal/c/parts/audio/framework.h
  source/global/version.bas
Labels: bug
