Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2024-12, with the labels that each got.

#582 Clamp and hsb colors
  internal/support/converter/AddPREFIX.bas
  internal/support/include/afterlastline.bm
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/colors/test.bas
  tests/compile_tests/colors/test.output
Labels: enhancement

#585 Update to latest supported llvm-mingw
  setup_mingw.cmd
Labels: enhancement

#587 Fixing compilation process
  .gitattributes
  source/global/constants.bas
  source/qb64pe.bas
  source/utilities/statevars.bas
  tests/compile_tests/auto_include/color0.bas
  tests/compile_tests/auto_include/color32.bas
Labels: bug, const-issues

#588 Lint and format markdown
  README.md
  docs/build-system.md
  docs/testing.md
Labels: documentation

#591 Libqb refactor
  Makefile
  internal/c/libqb.cpp
  internal/c/libqb/include/encoding.h
  internal/c/libqb/include/font.h
  internal/c/libqb/include/hashing.h
  internal/c/parts/audio/extras/foo_midi/InstrumentBankManager.cpp
  internal/c/parts/compression/build.mk
  internal/c/parts/compression/compression.cpp
  internal/c/parts/data/build.mk
  internal/c/parts/data/compression.cpp
  internal/c/parts/data/encoding.cpp
  internal/c/parts/data/miniz.c
  internal/c/parts/data/miniz.h
  internal/c/parts/data/modp_b64.cpp
  internal/c/parts/data/modp_b64.h
  internal/c/parts/data/modp_b64_data.h
  internal/c/parts/video/font/build.mk
  internal/c/parts/video/font/font.cpp
  internal/c/parts/video/font/hashing.cpp
  internal/c/qbx.cpp
  licenses/README.md
  licenses/license_modp_b64.txt
  source/qb64pe.bas
  source/subs_functions/subs_functions.bas
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/audio_out/test.lnx.license
  tests/compile_tests/audio_out/test.osx.license
  tests/compile_tests/audio_out/test.win.license
  tests/compile_tests/font/test.lnx.license
  tests/compile_tests/font/test.osx.license
  tests/compile_tests/font/test.win.license
  tests/compile_tests/hash/test.bas
  tests/compile_tests/libz/test.bas
  tests/compile_tests/libz/test.lnx.license
  tests/compile_tests/libz/test.osx.license
  tests/compile_tests/libz/test.output
  tests/compile_tests/libz/test.win.license
  tests/compile_tests/mem/mem_checking_off.bas
  tests/compile_tests/mem/mem_checking_off.output
Labels: enhancement
