Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2024-01, with the labels that each got.

#419 Filesystem refactor and update
  internal/c/common.h
  internal/c/libqb.cpp
  internal/c/libqb.h
  internal/c/libqb/build.mk
  internal/c/libqb/include/filepath.h
  internal/c/libqb/include/filesystem.h
  internal/c/libqb/src/filepath.cpp
  internal/c/libqb/src/filesystem.cpp
  internal/c/parts/audio/audio.cpp
  internal/c/parts/video/font/font.cpp
  internal/c/parts/video/image/image.cpp
  internal/c/qbx.cpp
  source/subs_functions/subs_functions.bas
  source/subs_functions/syntax_highlighter_list.bas
  tests/compile_tests/filesystem/filesys_test.bas
  tests/compile_tests/filesystem/filesys_test.output
Labels: bug, enhancement, libqb-refactor

#422 Upgrade miniaudio to v0.11.21
  internal/c/parts/audio/miniaudio.h
Labels: enhancement

#426 Make _FILES$() throw an error if it is called without an argument the first time
  internal/c/libqb/src/filesystem.cpp
Labels: bug

#428 Fix OPEN COM from locking up inside gfs_open_com_syntax()
  internal/c/libqb.cpp
Labels: bug

#430 Update stb_image to v2.29
  internal/c/parts/video/image/stb/stb_image.h
Labels: enhancement

#436 Remove dead code
  internal/c/libqb.cpp
  internal/c/time64.c
  internal/c/time64.h
Labels: libqb-refactor

#437 Fix FILES to work for cases where fileSpec$ does not contain a directory
  internal/c/libqb/src/filesystem.cpp
Labels: bug

#438 Export and meta refactoring
  source/ide/ide_methods.bas
  source/qb64pe.bas
  source/subs_functions/syntax_highlighter_list.bas
  source/utilities/elements.bas
Labels: enhancement

#440 Fix case-insensitive pattern matching on Windows and _FILES behavior
  internal/c/libqb/src/filesystem.cpp
Labels: bug

#442 Add external dependencies checks
  Makefile
  internal/source/data.bin
  source/ide/ide_methods.bas
  source/qb64pe.bas
  source/utilities/s-buffer/simplebuffer.bm
  source/utilities/strings.bas
Labels: enhancement
