Repository QB64-Phoenix-Edition/QB64pe, pull requests merged in 2025-01, with the labels that each got.

#594 libqb refactor and cleanup
  internal/c/common.h
  internal/c/libqb.cpp
  internal/c/libqb/build.mk
  internal/c/libqb/include/graphics.h
  internal/c/libqb/include/rounding.h
  internal/c/libqb/src/graphics.cpp
  internal/c/mtri1.cpp
  internal/c/mtri1s.cpp
  internal/c/mtri1t.cpp
  internal/c/mtri1ts.cpp
  internal/c/mtri2.cpp
  internal/c/mtri2s.cpp
  internal/c/mtri2t.cpp
  internal/c/mtri2ts.cpp
  internal/c/mtri3.cpp
  internal/c/mtri3s.cpp
  internal/c/mtri3t.cpp
  internal/c/mtri3ts.cpp
  internal/c/mtri4.cpp
  internal/c/mtri4s.cpp
  internal/c/mtri4t.cpp
  internal/c/mtri4ts.cpp
  internal/c/qbx.cpp
Labels: libqb-refactor

#596 Discord export
  internal/c/libqb.cpp
  source/ide/ide_export.bas
  source/ide/ide_methods.bas
Labels: enhancement

#598 Fix _CONSOLEINPUT function
  internal/c/libqb.cpp
Labels: bug

#599 Fix mouse _MOUSEMOVEMENTX/Y issue on Windows on ARM with C++ optimizations
  internal/c/parts/core/freeglut/freeglut_main.c
  setup_mingw.cmd
Labels: bug

#602 Disables mouse event suppression on macOS when the mouse is hidden and moved
  internal/c/libqb.cpp
  internal/c/libqb/include/filesystem.h
  internal/c/libqb/include/mac-mouse-support.h
  internal/c/libqb/src/filesystem.cpp
  internal/c/libqb/src/glut-message.cpp
  internal/c/libqb/src/graphics.cpp
  internal/c/libqb/src/mac-mouse-support.cpp
Labels: bug
